---
base_packages:
  - git
  - gitk
  - git-extras
  - vim

dotfiles_repo: 'https://github.com/opdavies/dotfiles3.git'
dotfiles_repo_local_destination: '~/.dotfiles'
dotfiles_files:
  - .gitconfig
  - .gitignore

ohmyzsh_users:
  - opdavies
ohmyzsh_theme: garyblessington
ohmyzsh_aliases:
  - zshconfig="vim ~/.zshrc"
  - ohmyzsh="vim ~/.oh-my-zsh"
ohmyzsh_plugins:
  - common-aliases
  - composer
  - gem
  - git
  - git-extras
  - git-flow
  - git-remote-branch
  - sublime
  - ubuntu
  - vagrant
