---
base_packages:
  - git
  - gitk
  - vim

dotfiles_repo: 'https://github.com/opdavies/dotfiles3.git'
dotfiles_repo_local_destination: '~/.dotfiles'
dotfiles_files:
  - .gitconfig
  - .gitignore

ohmyzsh_users:
  - opdavies
ohmyzsh_theme: garyblessington
