---
base_packages:
  - git
  - gitk
  - git-extras
  - git-sh
  - vim

dotfiles_repo: 'https://github.com/opdavies/dotfiles3.git'
dotfiles_repo_local_destination: '~/.dotfiles'
dotfiles_files:
  - .gitconfig
  - .gitignore-global

ohmyzsh_users:
  - opdavies
ohmyzsh_theme: garyblessington
ohmyzsh_aliases:
  - zshconfig="vim ~/.zshrc"
  - ohmyzsh="vim ~/.oh-my-zsh"
ohmyzsh_plugins:
  - common-aliases
  - git
  - git-extras
  - git-flow
  - sublime
  - ubuntu
  - vagrant

vagrant_packages:
  - nfs-common
  - nfs-kernel-server
  - virtualbox
  - vagrant

phpstorm_version: 9.0
