---
- hosts: localhost
  connection: local
  become: true

  vars:
    apt_packages:
      - name: ctop
      - name: curl
      - name: docker.io
      - name: docker-compose
      - name: fzf
      - name: htop
      - name: npm
      - name: php
      - name: python3-pip
      - name: pv
      - name: rename
      - name: ripgrep
      - name: stow
      - name: tmux
      - name: wget
      - name: zsh
    dotfiles_repo: https://github.com/opdavies/dotfiles
    dotfiles_stow_dir: ~/dotfiles
    pip_packages:
      - name: ansible-lint

  pre_tasks:
    -
      name: Update apt cache.
      apt:
        update_cache: yes
        cache_valid_time: 86400

  tasks:
    -
      name: Install and uninstall APT packages
      apt:
        name: "{{ item.name }}"
        state: "{{ item.state|default('latest') }}"
      with_items: "{{ apt_packages }}"
      tags: [apt]
    -
      name: Install and uninstall pip packages
      pip:
        name: "{{ item.name }}"
        executable: pip3
      with_items: "{{ pip_packages }}"
      tags: [pip]
    -
      include: tasks/zsh.yml
      tags: [zsh]
    -
      include: tasks/dotfiles.yml
      tags: [dotfiles]
    -
      include_role:
        name: neovim
      tags: [nvim, neovim]
    -
      include: tasks/npm.yml
      tags: [npm]
