---
- hosts: localhost
  connection: local
  become: true

  vars:
    apt_packages:
      - name: docker.io
      - name: docker-compose
      - name: fzf
      - name: geary
        state: absent
      - name: gir1.2-appindicator3-0.1 # Needed for screenkey
      - name: glances
      - name: gnome-sushi
      - name: htop
      - name: hub
      - name: meld
      - name: pdf-presenter-console
      - name: pdftk
      - name: php
      - name: screenkey
      - name: shutter
      - name: snapd
      - name: tmux
      - name: xclip
    pip_packages:
      - name: ansible-lint
      - name: rst2pdf
    snap_packages:
      - name: doctl # DigitalOcean CLI

  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: yes
        cache_valid_time: 86400 

  tasks:
    - name: Add the Shutter APT repository
      apt_repository:
        repo: ppa:linuxuprising/shutter
      tags: [apt]

    - name: Install and uninstall APT packages
      apt:
        name: "{{ item.name }}"
        state: "{{ item.state|default('latest') }}"
      with_items: "{{ apt_packages }}"
      tags: [apt]

    - name: Install and uninstall snap packages
      snap:
        name: "{{ item.name }}"
        state: "{{ item.state|default('present') }}"
      with_items: "{{ snap_packages }}"
      tags: [snap]

    - name: Install and uninstall pip packages
      pip:
        name: "{{ item.name }}"
        executable: pip3
      with_items: "{{ pip_packages }}"
      tags: [pip]

    - name: Add automation user
      user:
        name: jarvis
        comment: User for running automation commands
        system: yes
        state: present

    - name: Allow automation user to run ansible-pull
      lineinfile:
        path: /etc/sudoers
        state: present
        line: 'jarvis ALL=(ALL) NOPASSWD: /usr/local/bin/ansible-pull'
        validate: 'visudo -cf %s'

    - name: Add cron task for Ansible Pull
      cron:
        name: Ansible auto-provision
        user: jarvis
        minute: '*/10'
        job: ansible-pull --url https://github.com/opdavies/ubuntu-provisioning --only-if-changed
