---
- hosts: all
  become: true

  vars:
    apt_packages:
      - { name: fzf }
      - { name: geary, state: absent }
      - { name: gir1.2-appindicator3-0.1 } # Needed for screenkey
      - { name: screenkey }
    snap_packages:
      - { name: doctl } # DigitalOcean CLI

  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: yes
        cache_valid_time: 86400 

  tasks:
    - name: Install and uninstall APT packages
      apt:
        name: "{{ item.name }}"
        state: "{{ item.state|default('latest') }}"
      with_items: "{{ apt_packages }}"

    - name: Install and uninstall snap packages
      snap:
        name: "{{ item.name }}"
        state: "{{ item.state|default('present') }}"
      with_items: "{{ snap_packages }}"
