---
- hosts: all
  sudo: yes

  vars_files:
    - config.yml

  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: yes
        cache_valid_time: 86400 

  roles:
    - { role: base, tags: [ 'base', 'packages' ] }
    - { role: geerlingguy.dotfiles, tags: [ 'dotfiles' ] }
    - { role: opdavies.oh-my-zsh, tags: [ 'zsh', 'packages' ] }
    - { role: opdavies.sculpin, tags: [ 'sculpin', 'packages' ] }
    - { role: vagrant, tags: vagrant }
