---
- hosts: all
  sudo: yes

  vars_files:
    - config.yml

  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: yes
        cache_valid_time: 86400 

  roles:
    - base
    - { role: geerlingguy.dotfiles, tags: [ 'dotfiles' ] }
